# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  PYTHON: 'python3.8'
  INC_VER: '1.12'
  IMAGE_NAME: 'neural-compressor'
  IMAGE_TAG: '1.12'
  
steps:
- task: Docker@2
  displayName: Build Container
  inputs:
    command: build
    repository: ${IMAGE_NAME} # username/contosoRepository for DockerHub
    tags: ${IMAGE_TAG}
    arguments: PYTHON=${PYTHON},INC_VER=${INC_VER}
    Dockerfile: docker/Dockerfile


